//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulusCrmSync.LAKAServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LAKAServices.LAKAServicesSoap")]
    public interface LAKAServicesSoap {
        
        // CODEGEN: Generating message contract since element name Environment from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataSource", ReplyAction="*")]
        ModulusCrmSync.LAKAServices.GetDataSourceResponse GetDataSource(ModulusCrmSync.LAKAServices.GetDataSourceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataSource", ReplyAction="*")]
        System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.GetDataSourceResponse> GetDataSourceAsync(ModulusCrmSync.LAKAServices.GetDataSourceRequest request);
        
        // CODEGEN: Generating message contract since element name Environment from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CRMOrgService", ReplyAction="*")]
        ModulusCrmSync.LAKAServices.CRMOrgServiceResponse CRMOrgService(ModulusCrmSync.LAKAServices.CRMOrgServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CRMOrgService", ReplyAction="*")]
        System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.CRMOrgServiceResponse> CRMOrgServiceAsync(ModulusCrmSync.LAKAServices.CRMOrgServiceRequest request);
        
        // CODEGEN: Generating message contract since element name CRMOrgUsernameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CRMOrgUsername", ReplyAction="*")]
        ModulusCrmSync.LAKAServices.CRMOrgUsernameResponse CRMOrgUsername(ModulusCrmSync.LAKAServices.CRMOrgUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CRMOrgUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.CRMOrgUsernameResponse> CRMOrgUsernameAsync(ModulusCrmSync.LAKAServices.CRMOrgUsernameRequest request);
        
        // CODEGEN: Generating message contract since element name CRMOrgPasswordResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CRMOrgPassword", ReplyAction="*")]
        ModulusCrmSync.LAKAServices.CRMOrgPasswordResponse CRMOrgPassword(ModulusCrmSync.LAKAServices.CRMOrgPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CRMOrgPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.CRMOrgPasswordResponse> CRMOrgPasswordAsync(ModulusCrmSync.LAKAServices.CRMOrgPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name jobnavn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogStart", ReplyAction="*")]
        ModulusCrmSync.LAKAServices.LogStartResponse LogStart(ModulusCrmSync.LAKAServices.LogStartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogStart", ReplyAction="*")]
        System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.LogStartResponse> LogStartAsync(ModulusCrmSync.LAKAServices.LogStartRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataSourceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataSource", Namespace="http://tempuri.org/", Order=0)]
        public ModulusCrmSync.LAKAServices.GetDataSourceRequestBody Body;
        
        public GetDataSourceRequest() {
        }
        
        public GetDataSourceRequest(ModulusCrmSync.LAKAServices.GetDataSourceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataSourceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Environment;
        
        public GetDataSourceRequestBody() {
        }
        
        public GetDataSourceRequestBody(string Environment) {
            this.Environment = Environment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataSourceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataSourceResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModulusCrmSync.LAKAServices.GetDataSourceResponseBody Body;
        
        public GetDataSourceResponse() {
        }
        
        public GetDataSourceResponse(ModulusCrmSync.LAKAServices.GetDataSourceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataSourceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataSourceResult;
        
        public GetDataSourceResponseBody() {
        }
        
        public GetDataSourceResponseBody(string GetDataSourceResult) {
            this.GetDataSourceResult = GetDataSourceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CRMOrgServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CRMOrgService", Namespace="http://tempuri.org/", Order=0)]
        public ModulusCrmSync.LAKAServices.CRMOrgServiceRequestBody Body;
        
        public CRMOrgServiceRequest() {
        }
        
        public CRMOrgServiceRequest(ModulusCrmSync.LAKAServices.CRMOrgServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CRMOrgServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Environment;
        
        public CRMOrgServiceRequestBody() {
        }
        
        public CRMOrgServiceRequestBody(string Environment) {
            this.Environment = Environment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CRMOrgServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CRMOrgServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModulusCrmSync.LAKAServices.CRMOrgServiceResponseBody Body;
        
        public CRMOrgServiceResponse() {
        }
        
        public CRMOrgServiceResponse(ModulusCrmSync.LAKAServices.CRMOrgServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CRMOrgServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CRMOrgServiceResult;
        
        public CRMOrgServiceResponseBody() {
        }
        
        public CRMOrgServiceResponseBody(string CRMOrgServiceResult) {
            this.CRMOrgServiceResult = CRMOrgServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CRMOrgUsernameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CRMOrgUsername", Namespace="http://tempuri.org/", Order=0)]
        public ModulusCrmSync.LAKAServices.CRMOrgUsernameRequestBody Body;
        
        public CRMOrgUsernameRequest() {
        }
        
        public CRMOrgUsernameRequest(ModulusCrmSync.LAKAServices.CRMOrgUsernameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CRMOrgUsernameRequestBody {
        
        public CRMOrgUsernameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CRMOrgUsernameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CRMOrgUsernameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModulusCrmSync.LAKAServices.CRMOrgUsernameResponseBody Body;
        
        public CRMOrgUsernameResponse() {
        }
        
        public CRMOrgUsernameResponse(ModulusCrmSync.LAKAServices.CRMOrgUsernameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CRMOrgUsernameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CRMOrgUsernameResult;
        
        public CRMOrgUsernameResponseBody() {
        }
        
        public CRMOrgUsernameResponseBody(string CRMOrgUsernameResult) {
            this.CRMOrgUsernameResult = CRMOrgUsernameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CRMOrgPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CRMOrgPassword", Namespace="http://tempuri.org/", Order=0)]
        public ModulusCrmSync.LAKAServices.CRMOrgPasswordRequestBody Body;
        
        public CRMOrgPasswordRequest() {
        }
        
        public CRMOrgPasswordRequest(ModulusCrmSync.LAKAServices.CRMOrgPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CRMOrgPasswordRequestBody {
        
        public CRMOrgPasswordRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CRMOrgPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CRMOrgPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModulusCrmSync.LAKAServices.CRMOrgPasswordResponseBody Body;
        
        public CRMOrgPasswordResponse() {
        }
        
        public CRMOrgPasswordResponse(ModulusCrmSync.LAKAServices.CRMOrgPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CRMOrgPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CRMOrgPasswordResult;
        
        public CRMOrgPasswordResponseBody() {
        }
        
        public CRMOrgPasswordResponseBody(string CRMOrgPasswordResult) {
            this.CRMOrgPasswordResult = CRMOrgPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogStartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogStart", Namespace="http://tempuri.org/", Order=0)]
        public ModulusCrmSync.LAKAServices.LogStartRequestBody Body;
        
        public LogStartRequest() {
        }
        
        public LogStartRequest(ModulusCrmSync.LAKAServices.LogStartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogStartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jobnavn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string con;
        
        public LogStartRequestBody() {
        }
        
        public LogStartRequestBody(string jobnavn, string con) {
            this.jobnavn = jobnavn;
            this.con = con;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogStartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogStartResponse", Namespace="http://tempuri.org/", Order=0)]
        public ModulusCrmSync.LAKAServices.LogStartResponseBody Body;
        
        public LogStartResponse() {
        }
        
        public LogStartResponse(ModulusCrmSync.LAKAServices.LogStartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogStartResponseBody {
        
        public LogStartResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LAKAServicesSoapChannel : ModulusCrmSync.LAKAServices.LAKAServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LAKAServicesSoapClient : System.ServiceModel.ClientBase<ModulusCrmSync.LAKAServices.LAKAServicesSoap>, ModulusCrmSync.LAKAServices.LAKAServicesSoap {
        
        public LAKAServicesSoapClient() {
        }
        
        public LAKAServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LAKAServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LAKAServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LAKAServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModulusCrmSync.LAKAServices.GetDataSourceResponse ModulusCrmSync.LAKAServices.LAKAServicesSoap.GetDataSource(ModulusCrmSync.LAKAServices.GetDataSourceRequest request) {
            return base.Channel.GetDataSource(request);
        }
        
        public string GetDataSource(string Environment) {
            ModulusCrmSync.LAKAServices.GetDataSourceRequest inValue = new ModulusCrmSync.LAKAServices.GetDataSourceRequest();
            inValue.Body = new ModulusCrmSync.LAKAServices.GetDataSourceRequestBody();
            inValue.Body.Environment = Environment;
            ModulusCrmSync.LAKAServices.GetDataSourceResponse retVal = ((ModulusCrmSync.LAKAServices.LAKAServicesSoap)(this)).GetDataSource(inValue);
            return retVal.Body.GetDataSourceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.GetDataSourceResponse> ModulusCrmSync.LAKAServices.LAKAServicesSoap.GetDataSourceAsync(ModulusCrmSync.LAKAServices.GetDataSourceRequest request) {
            return base.Channel.GetDataSourceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.GetDataSourceResponse> GetDataSourceAsync(string Environment) {
            ModulusCrmSync.LAKAServices.GetDataSourceRequest inValue = new ModulusCrmSync.LAKAServices.GetDataSourceRequest();
            inValue.Body = new ModulusCrmSync.LAKAServices.GetDataSourceRequestBody();
            inValue.Body.Environment = Environment;
            return ((ModulusCrmSync.LAKAServices.LAKAServicesSoap)(this)).GetDataSourceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModulusCrmSync.LAKAServices.CRMOrgServiceResponse ModulusCrmSync.LAKAServices.LAKAServicesSoap.CRMOrgService(ModulusCrmSync.LAKAServices.CRMOrgServiceRequest request) {
            return base.Channel.CRMOrgService(request);
        }
        
        public string CRMOrgService(string Environment) {
            ModulusCrmSync.LAKAServices.CRMOrgServiceRequest inValue = new ModulusCrmSync.LAKAServices.CRMOrgServiceRequest();
            inValue.Body = new ModulusCrmSync.LAKAServices.CRMOrgServiceRequestBody();
            inValue.Body.Environment = Environment;
            ModulusCrmSync.LAKAServices.CRMOrgServiceResponse retVal = ((ModulusCrmSync.LAKAServices.LAKAServicesSoap)(this)).CRMOrgService(inValue);
            return retVal.Body.CRMOrgServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.CRMOrgServiceResponse> ModulusCrmSync.LAKAServices.LAKAServicesSoap.CRMOrgServiceAsync(ModulusCrmSync.LAKAServices.CRMOrgServiceRequest request) {
            return base.Channel.CRMOrgServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.CRMOrgServiceResponse> CRMOrgServiceAsync(string Environment) {
            ModulusCrmSync.LAKAServices.CRMOrgServiceRequest inValue = new ModulusCrmSync.LAKAServices.CRMOrgServiceRequest();
            inValue.Body = new ModulusCrmSync.LAKAServices.CRMOrgServiceRequestBody();
            inValue.Body.Environment = Environment;
            return ((ModulusCrmSync.LAKAServices.LAKAServicesSoap)(this)).CRMOrgServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModulusCrmSync.LAKAServices.CRMOrgUsernameResponse ModulusCrmSync.LAKAServices.LAKAServicesSoap.CRMOrgUsername(ModulusCrmSync.LAKAServices.CRMOrgUsernameRequest request) {
            return base.Channel.CRMOrgUsername(request);
        }
        
        public string CRMOrgUsername() {
            ModulusCrmSync.LAKAServices.CRMOrgUsernameRequest inValue = new ModulusCrmSync.LAKAServices.CRMOrgUsernameRequest();
            inValue.Body = new ModulusCrmSync.LAKAServices.CRMOrgUsernameRequestBody();
            ModulusCrmSync.LAKAServices.CRMOrgUsernameResponse retVal = ((ModulusCrmSync.LAKAServices.LAKAServicesSoap)(this)).CRMOrgUsername(inValue);
            return retVal.Body.CRMOrgUsernameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.CRMOrgUsernameResponse> ModulusCrmSync.LAKAServices.LAKAServicesSoap.CRMOrgUsernameAsync(ModulusCrmSync.LAKAServices.CRMOrgUsernameRequest request) {
            return base.Channel.CRMOrgUsernameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.CRMOrgUsernameResponse> CRMOrgUsernameAsync() {
            ModulusCrmSync.LAKAServices.CRMOrgUsernameRequest inValue = new ModulusCrmSync.LAKAServices.CRMOrgUsernameRequest();
            inValue.Body = new ModulusCrmSync.LAKAServices.CRMOrgUsernameRequestBody();
            return ((ModulusCrmSync.LAKAServices.LAKAServicesSoap)(this)).CRMOrgUsernameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModulusCrmSync.LAKAServices.CRMOrgPasswordResponse ModulusCrmSync.LAKAServices.LAKAServicesSoap.CRMOrgPassword(ModulusCrmSync.LAKAServices.CRMOrgPasswordRequest request) {
            return base.Channel.CRMOrgPassword(request);
        }
        
        public string CRMOrgPassword() {
            ModulusCrmSync.LAKAServices.CRMOrgPasswordRequest inValue = new ModulusCrmSync.LAKAServices.CRMOrgPasswordRequest();
            inValue.Body = new ModulusCrmSync.LAKAServices.CRMOrgPasswordRequestBody();
            ModulusCrmSync.LAKAServices.CRMOrgPasswordResponse retVal = ((ModulusCrmSync.LAKAServices.LAKAServicesSoap)(this)).CRMOrgPassword(inValue);
            return retVal.Body.CRMOrgPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.CRMOrgPasswordResponse> ModulusCrmSync.LAKAServices.LAKAServicesSoap.CRMOrgPasswordAsync(ModulusCrmSync.LAKAServices.CRMOrgPasswordRequest request) {
            return base.Channel.CRMOrgPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.CRMOrgPasswordResponse> CRMOrgPasswordAsync() {
            ModulusCrmSync.LAKAServices.CRMOrgPasswordRequest inValue = new ModulusCrmSync.LAKAServices.CRMOrgPasswordRequest();
            inValue.Body = new ModulusCrmSync.LAKAServices.CRMOrgPasswordRequestBody();
            return ((ModulusCrmSync.LAKAServices.LAKAServicesSoap)(this)).CRMOrgPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ModulusCrmSync.LAKAServices.LogStartResponse ModulusCrmSync.LAKAServices.LAKAServicesSoap.LogStart(ModulusCrmSync.LAKAServices.LogStartRequest request) {
            return base.Channel.LogStart(request);
        }
        
        public void LogStart(string jobnavn, string con) {
            ModulusCrmSync.LAKAServices.LogStartRequest inValue = new ModulusCrmSync.LAKAServices.LogStartRequest();
            inValue.Body = new ModulusCrmSync.LAKAServices.LogStartRequestBody();
            inValue.Body.jobnavn = jobnavn;
            inValue.Body.con = con;
            ModulusCrmSync.LAKAServices.LogStartResponse retVal = ((ModulusCrmSync.LAKAServices.LAKAServicesSoap)(this)).LogStart(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.LogStartResponse> ModulusCrmSync.LAKAServices.LAKAServicesSoap.LogStartAsync(ModulusCrmSync.LAKAServices.LogStartRequest request) {
            return base.Channel.LogStartAsync(request);
        }
        
        public System.Threading.Tasks.Task<ModulusCrmSync.LAKAServices.LogStartResponse> LogStartAsync(string jobnavn, string con) {
            ModulusCrmSync.LAKAServices.LogStartRequest inValue = new ModulusCrmSync.LAKAServices.LogStartRequest();
            inValue.Body = new ModulusCrmSync.LAKAServices.LogStartRequestBody();
            inValue.Body.jobnavn = jobnavn;
            inValue.Body.con = con;
            return ((ModulusCrmSync.LAKAServices.LAKAServicesSoap)(this)).LogStartAsync(inValue);
        }
    }
}
